### ISSUE TITLE
Readable Content Width?

### ISSUE THREAD

**Issue by winkelsdorf** [enricenrich/EECellSwipeGestureRecognizer#1]
Hi,

what a great, clean swiftly approach! 

One issue: It does not support the readable width with iOS9. To reproduce set each cell in the demo to:

```
cell.preservesSuperviewLayoutMargins = true
cell.contentView.preservesSuperviewLayoutMargins = true
```

and the tableView in viewDidLoad to:

```
tableView.cellLayoutMarginsFollowReadableWidth = true
```

**Expected**
The Swipe should only take place within the cell's contentView bounds. 

**Actually**
<img width="1136" alt="screenshot 2016-04-24 15 27 15" src="https://cloud.githubusercontent.com/assets/1413291/14767873/4abcb0ca-0a31-11e6-857f-b043b0ebaa8a.png">

Cheers,
Frederik

**Comment by enricenrich** [comment]
@winkelsdorf Thanks for the report! Will definitively take a look to it this weekend! :)

**Comment by winkelsdorf** [comment]
@enricenrich Thanks for the follow up, glad to hear that! 

_But_ on the other hand I had some time to evaluate the system provided default row edit action and some other swipe gesture components: All of them start off the frame corner of the `UITableView`. So my expectation was wrong, I was too picky about the perfect design.

So, if it's not something doable within 30 minutes, I would say drop it and keep this issue archived as feature request. If more want it, reconsider doing it.

Just to save _your_ valuable time! it's weekend, time to close Xcode for a few hours ;)

As a workaround I simply decreased the width of the TableView, layouted it to the readable content guide if available (and fallback to code constraints of approx. 30%/70% with iOS8). Together with forwarding outside scrolls via a hit test and delegate to the target table this works.

Cheers,
Frederik

P.S.: Leaving it up to you to close this.

**Comment by enricenrich** [comment]
@winkelsdorf I just took a look to it, and like you say, other swipe gesture components, and even the native ones, start off the frame corner.

I tried to find a way to offer an option to customize it and make it work like you say, but it's not possible because the gesture recognizer moves the content view of the cell, and the content view of the cell is full width, from edge to edge of the table view.

What I recommend you to do if possible (I'm not sure right now), is customize the content view of the cell to change the width of it to match the readable content guide.

Anyway, thanks for reaching out and let me know if you find any other issue! By the way, I'm pushing a new version now with minor code changes for the upcoming Swift 3 release mainly.
